---
title: An R Markdown document converted from "Stage2ProjectReport.ipynb"
output: html_document
---

# Data Analysis

```{r}
library(dplyr)
library(car)
library(ggplot2)
library(rmarkdown)
```

```{r}
dataset_url <- "https://raw.githubusercontent.com/wilkmzhou/STAT306_PROJECT_REPORT_2026/refs/heads/main/mercedes_benz_listings_cleaned.csv" # load dataset from github

benzDataRaw <- read.csv(dataset_url)                                                                                                        # read dataset
head(benzDataRaw, n = 3)
```

```{r}
benzData <- benzDataRaw |> 
    na.omit() |>                                                                                              # remove any NA rows 
    select(-Price_Per_Mile, -Price_Category, -Year, -Mileage_Category, -Vehicle_Name, -Model_Series, -Is_AMG) |> # remove redundant variables
    select(-Trim_Level, -Is_4MATIC)                                                                           # remove uninterested variables
head(benzData, n = 3)
```

# Exploratory Data Analysis
## Numerical Variables
### Correlation Plot

```{r}
benzDataInt <- benzData |>
    select(-Body_Type) # filter dataset from categorical variables

pairs(benzDataInt) # scatterplot between each pair of numerical variables
cor(benzDataInt) # correlation between each pair of numerical variables
```

```{r}
benzDataTransf <- benzDataInt |>
    transmute(log_Vehicle_Age = log(Vehicle_Age), log_Mileage_Miles = log(Mileage_Miles), log_Price_USD = log(Price_USD)) # transform variables 

pairs(benzDataTransf)                                                                                                     # find correlation between variables
cor(benzDataTransf)
```

### Categorical Variables

```{r}
options(repr.plot.width = 8, repr.plot.height = 5)
benzDataCat <- benzData |>
    select(-Vehicle_Age, -Mileage_Miles) # filter dataset from numerical variables

benzBodyBoxplot <- benzDataCat |>
    ggplot(aes(x = Body_Type, y = Price_USD)) + 
    geom_boxplot() + 
    ylab("Price in USD") + # y-axis label change 
    xlab("Vehicle Body Type") + # x-axis label change
    ggtitle("Vehicle Price and Body Type Boxplot") + # title
    theme(plot.title = element_text(hjust = 0.5, face = "bold"), text = element_text(size = 12)) # title alignment and text size increase

benzBodyBoxplot
```

### Fitting Linear Regression Model 1 (no variable transforming)

```{r}
benzFit1 <- lm(Price_USD ~ ., data = benzData) # fit linear regression model with all variables in filtered dataset

summary(benzFit1) # print linear regression fit statistics
```

### Check Linear Regression VIF

```{r}
vifBenz <- vif(benzFit1)
vifBenz
```

### Residuals and Fitted Values Scatterplot

```{r}
options(repr.plot.width = 6, repr.plot.height = 5)
plot(fitted(benzFit1), resid(benzFit1), main = "Residual Plot with Fitted Values from Fit1", xlab = "Fitted Values", ylab = "Residuals") # plot fitted values and residuals
abline(0,0)                                                                                                                              # add horizontal line at 0 
```

### Another Fitted Model to Address Heteroscedasticity

```{r}
benzFit2 <- lm(log(Price_USD) ~ log(Vehicle_Age) + log(Mileage_Miles) + Body_Type, data = benzData) # fit linear regression with transformed variables

summary(benzFit2)
```

### New Residuals and Fitted Values Scatterplot 

```{r}
plot(fitted(benzFit2), resid(benzFit2), main = "Residual Plot with Fitted Values from Fit1", xlab = "Fitted Values", ylab = "Residuals") # plot fitted values and residuals
abline(0,0)  
```

```{r}
vifBenzFit2 <- vif(benzFit2) # compute vif of fit with transformed variables

vifBenzFit2 
```

### QQ Plot

```{r}
resFit1 <- resid(benzFit1)
resFit2 <- resid(benzFit2)

qqnorm(resFit2) # display QQ plot of linear regression with 
qqline(resFit2)

qqnorm(resFit1)
qqline(resFit1)
```

```{r}
rmarkdown::convert_ipynb("Stage2ProjectReport.ipynb")
```

```{r}
knitr::purl("Stage2ProjectReport.Rmd")
```

